# Generated by Django 4.0.2 on 2022-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='d_o_b',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
